
tasks:
  ProcessVideos:
    dataset_videos_path: "data/CrossDatasetVideos"
    dataset_frames_path: "data/CrossDatasetFrames"
  
  ExtractKeypoints:
    dataset_frames_path: "data/CrossDatasetFrames"
    dataset_path: "data/CrossDatasetFilesCSV"
  
  SplitDataset:
    dataset_path: "data/CrossDatasetFilesCSV/angles_distances/full_dataset.csv"

  TrainModel:
    train_dataset_path: "data/CrossDatasetFilesCSV/angles_distances/train.csv"
    val_dataset_path:   "data/CrossDatasetFilesCSV/angles_distances/val.csv"
    output_folder_path: "runs"
  
  TestModel:
    test_dataset_path: "data/CrossDatasetFilesCSV/angles_distances/test.csv"
    model_path: "runs/run16/model_best.pth"
